openapi: 3.0.3
info:
  title: Choreo Samples - Reading List - Python REST API
  description: >-
    This is a sample API specification for a simple reading list application with in-memory cache
    written in Python.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Choreo
  url: https://choreo.dev
servers:
  - url: http://localhost:5000
tags:
  - name: books
    description: In-memory book list cache API
paths:
  /books:
    summary: List all books
    get:
      summary: List all books
      operationId: ListAllBooks
      tags:
        - books
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StringArray"



components:
  schemas:
    Key:
      type: object
      properties:
        id:
          type: string
          example: "my-id"
    Status:
      type: object
      properties:
        status:
          type: string
          example: "read"
    KeyValue:
      type: object
      required:
        - name
        - author
        - status
      properties:
        name:
          type: string
          example: "my-name"
        author:
          type: string
          example: "my-author"
        status:
          type: string
          example: "read"
    StringArray:
      type: array
      items:
        type: string